In [1]:
import torch

In [3]:
# Создайте случайный FloatTensor размера 3x4x5
x=torch.FloatTensor(3,4,5)
x

tensor([[[ 7.1305e+31,  1.3593e-43,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  1.9069e+15,  4.5818e-41,  1.5469e+19,  4.5818e-41],
         [ 1.5469e+19,  4.5818e-41,  1.5469e+19,  4.5818e-41,  1.2534e+19],
         [ 4.5818e-41,  3.5733e-43,  0.0000e+00,  1.4013e-45,  0.0000e+00]],

        [[ 1.5469e+19,  4.5818e-41,  1.5469e+19,  4.5818e-41,  1.4013e-45],
         [ 0.0000e+00,  3.5733e-43,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 1.5469e+19,  4.5818e-41,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  3.5733e-43,  0.0000e+00,  0.0000e+00, -4.6566e-10],
         [-9.9124e-26,  1.0845e-19,  9.8091e-45,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  3.5733e-43,  0.0000e+00,  0.0000e+00,  0.0000e+00]]])

In [5]:
# Выведите его форму (shape)
x.shape

torch.Size([3, 4, 5])

In [7]:
# Приведите его к форме 6 X 10
x.view(6,10)

tensor([[ 7.1305e+31,  1.3593e-43,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  1.9069e+15,  4.5818e-41,  1.5469e+19,  4.5818e-41],
        [ 1.5469e+19,  4.5818e-41,  1.5469e+19,  4.5818e-41,  1.2534e+19,
          4.5818e-41,  3.5733e-43,  0.0000e+00,  1.4013e-45,  0.0000e+00],
        [ 1.5469e+19,  4.5818e-41,  1.5469e+19,  4.5818e-41,  1.4013e-45,
          0.0000e+00,  3.5733e-43,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 1.5469e+19,  4.5818e-41,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  3.5733e-43,  0.0000e+00,  0.0000e+00, -4.6566e-10],
        [-9.9124e-26,  1.0845e-19,  9.8091e-45,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  3.5733e-43,  0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [10]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно
x * torch.Tensor([1,4,2,2,1])

tensor([[[ 7.1305e+31,  5.4370e-43,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  7.6275e+15,  9.1637e-41,  3.0938e+19,  4.5818e-41],
         [ 1.5469e+19,  1.8327e-40,  3.0938e+19,  9.1637e-41,  1.2534e+19],
         [ 4.5818e-41,  1.4293e-42,  0.0000e+00,  2.8026e-45,  0.0000e+00]],

        [[ 1.5469e+19,  1.8327e-40,  3.0938e+19,  9.1637e-41,  1.4013e-45],
         [ 0.0000e+00,  1.4293e-42,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 1.5469e+19,  1.8327e-40,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  1.4293e-42,  0.0000e+00,  0.0000e+00, -4.6566e-10],
         [-9.9124e-26,  4.3379e-19,  1.9618e-44,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  1.4293e-42,  0.0000e+00,  0.0000e+00,  0.0000e+00]]])

In [11]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
x6_10 = x.view(6,10)
y = torch.matmul(x6_10, x6_10.t())
y.size()

torch.Size([6, 6])

In [12]:
y

tensor([[        inf,         inf,         inf,         inf,  6.8139e-28,
         -7.0681e+06],
        [        inf,         inf,         inf,  2.3929e+38,  0.0000e+00,
         -1.5333e-06],
        [        inf,         inf,         inf,  2.3929e+38,  0.0000e+00,
         -1.5333e-06],
        [        inf,  2.3929e+38,  2.3929e+38,  2.3929e+38,  0.0000e+00,
         -1.5333e-06],
        [ 6.8139e-28,  0.0000e+00,  0.0000e+00,  0.0000e+00,  2.1684e-19,
          0.0000e+00],
        [-7.0681e+06, -1.5333e-06, -1.5333e-06, -1.5333e-06,  0.0000e+00,
          1.1761e-38]])

In [19]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
from torch.autograd import Variable

x = Variable(torch.FloatTensor([1.0]), requires_grad = True)
z = Variable(torch.FloatTensor([0.5]), requires_grad = True)
t = Variable(torch.FloatTensor([2.0]), requires_grad = True)
y = x**3 + z - 75*t

y.backward()

print(f'y_x={x.grad}')
print(f'y_z={z.grad}')
print(f'y_t={t.grad}')

y_x=tensor([3.])
y_z=tensor([1.])
y_t=tensor([-75.])


In [21]:
# Создайте единичный тензор размера 5x6

x = torch.ones(5,6)
x

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [23]:
# Переведите его в формат numpy
x.numpy()

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

In [67]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте

from torch import nn 
from torch import optim

w1 = Variable(torch.Tensor([0.1,0.1]), requires_grad = True)
x = Variable(torch.Tensor([2,2]), requires_grad = False)
y = Variable(torch.Tensor([2,2]), requires_grad = False)

In [68]:
optimizer = torch.optim.SGD([w1], lr=0.01)
criterion = torch.nn.MSELoss()

In [69]:
func = x**w1 - 2 * x**2 + 5

optimizer.zero_grad()
pred = func
loss = criterion(pred, y)

loss.backward()     
optimizer.step()    

In [71]:
print(f'loss:\t {loss.item()}')
print(f'w1:\t {w1.data}')

loss:	 15.430963516235352
w1:	 tensor([0.1292, 0.1292])
